version: '3'

services:
    drupal:
        image: drupal:latest
        ports:
            -"8080:80"
        volumes:
            - drupal-profile:/var/www/html/profiles
            - drupal-theme:/var/www/html/themes
            # this takes advantage of the feature in Docker that a new anonymous
            # volume (which is what we're creating here) will be initialized with the
            # existing content of the image at the same location
            - drupal-site:/var/www/html/sites
            - drupal-module:/var/www/html/modules

    postgres:
        image: postgres:10
        environment:
            POSTGRES_PASSWORD=example